---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playapp
  labels:
    app: playapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playapp
  template:
    metadata:
      labels:
        app: playapp
    spec:
      containers:
      - name: playapp
        image: mzesri/contour-sample:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 9000
        - name: https
          containerPort: 9443
        - name: debug
          containerPort: 8000
        env:
        - name: EXTERNAL_HOSTNAME
          value: a4iot-mingwebsockettest.westus2.cloudapp.azure.com
        resources:
          limits:
            cpu: '8'
            memory: 8Gi
          requests:
            cpu: '1'
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: playapp-service
  labels:
    app: playapp
spec:
  ports:
  - name: http
    port: 80
    targetPort: 9000
    protocol: TCP
  selector:
    app: playapp
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata: 
  name: playapp-ingress-route 
  namespace: default
spec: 
  virtualhost:
    fqdn: a4iot-mingwebsockettest.westus2.cloudapp.azure.com
    tls:
      secretName: a4iot-cert
      minimumProtocolVersion: "1.2"
  routes: 
    - conditions:
      - prefix: /prefix/
      timeoutPolicy:
        response: 900s
        idle: 900s
      enableWebsockets: true
      permitInsecure: true
      services:
        - name: playapp-service
          port: 80
      pathRewritePolicy:
        replacePrefix:
          - prefix: /prefix/
            replacement: /
      retryPolicy:
        count: 3

